version: '1'

services:
  postgres-app:
    image: postgres:16.2
    environment:
       POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
       POSTGRES_USER: ${POSTGRES_USERNAME}
       POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_DB_PORT}:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./sqlScript/test.sql:/docker-entrypoint-initdb.d/test.sql

  my-app:
    build: .

volumes:
  postgres-data:
